---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jms-ssh-claim

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jms-api-svc

spec:
  ports:
    - port: 6060
      targetPort: 6060
      protocol: TCP
      name: pprof
    - port: 8013
      targetPort: 8013
      protocol: TCP
      name: api
  type: ClusterIP
  selector:
    app: jms-api
---
apiVersion: v1
kind: Service
metadata:
  name: jms-sshd-svc

spec:
  ports:
    - port: 22222
      targetPort: 22222
      protocol: TCP
      name: ssh
    - port: 6060
      targetPort: 6060
      protocol: TCP
      name: pprof
  type: ClusterIP
  selector:
    app: jms-sshd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jms-config

data:
  config.yaml: |
    # 请查看 config.yaml 的配置后在此配置。

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jms-api-deployment
  labels:
    app: jms-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jms-api
  template:
    metadata:
      labels:
        app: jms-api
    spec:
      containers:
        - name: jms-api
          image: zhoushoujian/jms:latest
          imagePullPolicy: Always
          env:
            - name: API
              value: "true"
          volumeMounts:
            - mountPath: /opt/jms/config.yaml
              subPath: config.yaml
              name: jms-config-volume
              readOnly: true
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 0.1
              memory: 256Mi
          ports:
            - name: api
              containerPort: 8013
              protocol: TCP
      volumes:
        - name: jms-config-volume
          configMap:
            name: jms-config
        - name: ssh-volume
          persistentVolumeClaim:
            claimName: jms-ssh-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jms-sshd-deployment
  labels:
    app: jms-sshd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jms-sshd
  template:
    metadata:
      labels:
        app: jms-sshd
    spec:
      containers:
        - name: jms-sshd
          image: zhoushoujian/jms:latest
          imagePullPolicy: Always
          env:
            - name: WITH_SSH_CHECK
              value: "true"
            - name: SSH_DIR
              value: /opt/jms/.ssh/
          volumeMounts:
            - mountPath: /opt/jms/
              name: ssh-volume
            - mountPath: /opt/logs/
              name: logs-volume
            - mountPath: /opt/jms/config.yaml
              subPath: config.yaml
              name: jms-config-volume
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 0.1
              memory: 256Mi
          ports:
            - name: ssh
              containerPort: 22222
              protocol: TCP
      volumes:
        - name: jms-config-volume
          configMap:
            name: jms-config
        - name: ssh-volume
          persistentVolumeClaim:
            claimName: jms-ssh-claim
        - name: logs-volume
          hostPath:
            path: /mnt/logs/jms-sshd/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jms-schedule-deployment
  labels:
    app: jms-schedule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jms-schedule
  template:
    metadata:
      labels:
        app: jms-schedule
    spec:
      containers:
        - name: jms-schedule
          image: zhoushoujian/jms:latest
          imagePullPolicy: Always
          env:
            - name: SCHEDULE
              value: "true"
            - name: DEBUG
              value: "false"
            - name: JMS_DINGTALK_WEB_HOOK_TOKEN
              value: ""
          volumeMounts:
            - mountPath: /opt/jms/config.yaml
              subPath: config.yaml
              name: jms-config-volume
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 0.1
              memory: 256Mi
      volumes:
        - name: jms-config-volume
          configMap:
            name: jms-config
