version: "3"
services: 
  pg:
    image: postgres
    restart: always
    hostname: pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jms
    ports:
      - "5432:5432"
  jms:
    depends_on:
      - pg
    restart: always
    image: zhoushoujian/jms:latest
    ports: 
      - "22222:22222"
    environment:
      - TIMEOUT=1800
      - DEBUG=false
      - API=false
    volumes: 
      - "./config.yaml:/opt/jms/config.yaml"
      - "/opt/jms/.ssh/:/opt/jms/.ssh/" # 持久化数据
  jms-api:
    depends_on:
      - pg
    restart: always
    image: zhoushoujian/jms:latest
    ports: 
      - "8013:8013"
    environment:
      - DEBUG=false
      - API=true # true为api模式，false为ssh服务模式
    volumes: 
      - "./config.yaml:/opt/jms/config.yaml"
      - "/opt/jms/.ssh/:/opt/jms/.ssh/" # 持久化数据