version: "3"
services: 
  jms:
    restart: always
    image: zhoushoujian/jms:latest
    ports: 
      - "22222:22222"
    volumes: 
      - "/data/ssh:/root/.ssh"
      - "/opt/jms/:/opt/jms/"
      - "/mnt/logs/s-ops-jms/:/opt/logs/"
