apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jms-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jms
  serviceName: jms
  template:
    metadata:
      labels:
        app: jms
    spec:
      nodeSelector:
        env: jms-v2
      containers:
        - name: jms-api
          image: zhoushoujian/jms:latest
          imagePullPolicy: Always
          cmd:
            - jms-go api
          env:
            - name : WITH_SSH_CHECK
              value: "true"
            - name: SSH_DIR
              value: /opt/jms/.ssh/
          volumeMounts:
            - mountPath: /opt/jms/.jms.yml
              subPath: .jms.yml
              name: jms-config-volume
              readOnly: true
            - mountPath: /opt/jms/
              name: ssh-volume

          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 0.1
              memory: 256Mi
          ports:
            - name: api
              containerPort: 8013
              protocol: TCP


        - name: jms
          image: zhoushoujian/jms:latest
          imagePullPolicy: Always
          env:
            - name : WITH_SSH_CHECK
              value: "true"
            - name: SSH_DIR
              value: /opt/jms/.ssh/
          volumeMounts:
            - mountPath: /opt/jms/
              name: ssh-volume
            - mountPath: /opt/logs/
              name: logs-volume
              readOnly: false
            - mountPath: /opt/jms/.jms.yml
              subPath: .jms.yml
              name: jms-config-volume
              readOnly: true
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 0.1
              memory: 256Mi
          ports:
            - name: ssh
              containerPort: 22222
              protocol: TCP
      volumes:
        - name: jms-config-volume # 安全原因 configmap.yaml是没有上传的，需要自己去集群修改。
          configMap:
            name: jms-config
        - name: ssh-volume
          persistentVolumeClaim:
            claimName: jms-ssh-claim
        - name: logs-volume
          hostPath:
            path: /mnt/logs/jms-tools/
      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jms-ssh-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jms
spec:
  ports:
    - port: 22222
      targetPort: 22222
      nodePort: 32222
      protocol: TCP
      name: ssh
    - port: 80
      targetPort: 8013
      protocol: TCP
      name: api
  selector:
    app: jms
  type: NodePort