apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jms-statefulset

spec:
  replicas: 1
  selector:
    matchLabels:
      app: jms
  serviceName: jms
  template:
    metadata:
      name: jms
      labels:
        app: jms
    spec:
      containers:
        - name: jms-api
          image: zhoushoujian/jms:latest
          imagePullPolicy: Always
          env:
            - name: API
              value: "true"
          volumeMounts:
            - mountPath: /opt/jms/config.yaml
              subPath: config.yaml
              name: jms-config-volume
              readOnly: true
            - mountPath: /opt/jms/
              name: ssh-volume
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 0.1
              memory: 256Mi
          ports:
            - name: api
              containerPort: 8013
              protocol: TCP

        - name: jms
          image: zhoushoujian/jms:latest
          imagePullPolicy: Always
          env:
            - name: WITH_SSH_CHECK
              value: "true"
            - name: SSH_DIR
              value: /opt/jms/.ssh/
          volumeMounts:
            - mountPath: /opt/jms/
              name: ssh-volume
            - mountPath: /opt/logs/
              name: logs-volume
              readOnly: false
            - mountPath: /opt/jms/config.yaml
              subPath: config.yaml
              name: jms-config-volume
              readOnly: true
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 0.1
              memory: 256Mi
          ports:
            - name: ssh
              containerPort: 22222
              protocol: TCP
      volumes:
        - name: jms-config-volume # 安全原因 configmap.yaml是没有上传的，需要自己去集群修改。
          configMap:
            name: jms-config
        - name: ssh-volume
          persistentVolumeClaim:
            claimName: s-ops-jms-ssh-claim
        - name: logs-volume
          hostPath:
            path: /mnt/logs/jms-tools/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jms-ssh-claim

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jms-svc

spec:
  ports:
    - port: 22222
      targetPort: 22222
      protocol: TCP
      name: ssh
    - port: 8013
      targetPort: 8013
      protocol: TCP
      name: api
  type: NodePort

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jms-config

data:
  config.yaml: |
    # 请查看 config.yaml 的配置后在此配置。
